version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - cmd: dotnet build
build_script:
  - cmd: dotnet publish C:\projects\zato-wot\Zato.WOT.Console\Zato.WOT.Console.csproj
after_build:
  # For once the build has completed
#artifacts:
# - path: '\src\bin\Debug\netcoreapp1.1\publish'
#   name: WebSite
#   type: WebDeployPackage
clone_depth: 1
test_script:
  # run the unit tests (requires changing into the test directory)
  - cmd: cd C:\projects\zato-wot\Zato.WOT.xUnit
  - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off