version: '1.0.{build}'
image: Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Release
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore
  - cmd: dotnet build
build_script:
  - cmd: dotnet publish %APPVEYOR_BUILD_FOLDER%\Zato.WOT.Console\Zato.WOT.Console.csproj
after_build:
  - cmd: 7z a zato.zip "%APPVEYOR_BUILD_FOLDER%\Zato.WOT.Console\bin\Any CPU\Release\netcoreapp2.0\publish\*"
artifacts:
  - path: zato.zip
    name: zatowot
clone_depth: 1
deploy:
  release: ZatoWOT-v$(appveyor_build_version)
  description: 'Preview'
  provider: GitHub
  auth_token:
    secure: NJjwo5e5lMYs1LKiiIakjtna/eOFsOWF5F1ICWz8+oLGIDIBd/dkUPiXmHl0RK+c
  artifact: zato.zip
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
